'use client';

import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import styles from './coming-soon.module.css';

type Ingredient = {
  src: string;
  style: CSSProperties & Record<string, string>;
};

const ingredients: Ingredient[] = [
  // ── FAR LEFT (0–14vw) ──────────────────────────────────────

  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '5.8vw',
      '--y': '32.4vh',
      '--w': '5.2rem',
      '--r': '-22deg',
      '--rainDelay': '0.58s',
      '--rainDuration': '1.32s',
      '--fall': '76vh',
      '--duration': '8.1s',
      '--blur': '0.6px',
      '--opacity': '0.72',
      '--dx': '-0.42rem',
      '--dy': '-0.72rem',
      '--spin': '6deg',
      '--px': '-1.2rem',
      '--py': '-0.65rem',
    },
  },
  {
    src: '/PNG/CHOCOLATE.png',
    style: {
      '--x': '3.6vw',
      '--y': '54.2vh',
      '--w': '4.8rem',
      '--r': '17deg',
      '--rainDelay': '0.84s',
      '--rainDuration': '1.28s',
      '--fall': '84vh',
      '--duration': '7.9s',
      '--blur': '0.4px',
      '--opacity': '0.68',
      '--dx': '0.38rem',
      '--dy': '-0.68rem',
      '--spin': '-5deg',
      '--px': '0.85rem',
      '--py': '0.52rem',
    },
  },
  {
    src: '/PNG/JAGGERY.png',
    style: {
      '--x': '8.4vw',
      '--y': '72.6vh',
      '--w': '4.2rem',
      '--r': '-35deg',
      '--rainDelay': '0.42s',
      '--rainDuration': '1.22s',
      '--fall': '90vh',
      '--duration': '8.4s',
      '--blur': '1.2px',
      '--opacity': '0.54',
      '--dx': '-0.32rem',
      '--dy': '-0.6rem',
      '--spin': '8deg',
      '--px': '0.78rem',
      '--py': '0.46rem',
    },
  },


  // ── LEFT–CENTER (15–29vw) ────────────────────────────────────

  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '20.8vw',
      '--y': '42.6vh',
      '--w': '2.8rem',
      '--r': '66deg',
      '--rainDelay': '0.72s',
      '--rainDuration': '1.08s',
      '--fall': '74vh',
      '--duration': '6.8s',
      '--blur': '1.6px',
      '--opacity': '0.5',
      '--dx': '-0.22rem',
      '--dy': '-0.42rem',
      '--spin': '-10deg',
      '--px': '0.58rem',
      '--py': '0.36rem',
    },
  },
  {
    src: '/PNG/DATES.png',
    style: {
      '--x': '24.6vw',
      '--y': '62.4vh',
      '--w': '7.2rem',
      '--r': '-12deg',
      '--rainDelay': '0.18s',
      '--rainDuration': '1.42s',
      '--fall': '88vh',
      '--duration': '9s',
      '--blur': '0.8px',
      '--opacity': '0.64',
      '--dx': '0.44rem',
      '--dy': '-0.82rem',
      '--spin': '5deg',
      '--px': '1.1rem',
      '--py': '0.62rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '27.4vw',
      '--y': '22.8vh',
      '--w': '4.6rem',
      '--r': '33deg',
      '--rainDelay': '0.96s',
      '--rainDuration': '1.26s',
      '--fall': '72vh',
      '--duration': '7.6s',
      '--blur': '1.1px',
      '--opacity': '0.6',
      '--dx': '-0.35rem',
      '--dy': '-0.64rem',
      '--spin': '-6deg',
      '--px': '-0.88rem',
      '--py': '-0.52rem',
    },
  },

  // ── CENTER (30–49vw) ─────────────────────────────────────────
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '30.4vw',
      '--y': '13.2vh',
      '--w': '2.6rem',
      '--r': '63deg',
      '--rainDelay': '0.31s',
      '--rainDuration': '1.08s',
      '--fall': '64vh',
      '--duration': '6.5s',
      '--blur': '1.8px',
      '--opacity': '0.55',
      '--dx': '-0.22rem',
      '--dy': '-0.42rem',
      '--spin': '-9deg',
      '--px': '-0.65rem',
      '--py': '-0.36rem',
    },
  },
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '36.2vw',
      '--y': '5.2vh',
      '--w': '4.1rem',
      '--r': '-31deg',
      '--rainDelay': '0.12s',
      '--rainDuration': '1.24s',
      '--fall': '62vh',
      '--duration': '7.6s',
      '--blur': '1.2px',
      '--opacity': '0.74',
      '--dx': '0.35rem',
      '--dy': '-0.7rem',
      '--spin': '5deg',
      '--px': '-1.1rem',
      '--py': '-0.65rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '39.4vw',
      '--y': '14.1vh',
      '--w': '6.6rem',
      '--r': '11deg',
      '--rainDelay': '0.28s',
      '--rainDuration': '1.38s',
      '--fall': '72vh',
      '--duration': '8.2s',
      '--blur': '0',
      '--opacity': '0.96',
      '--dx': '0.6rem',
      '--dy': '-0.9rem',
      '--spin': '-4deg',
      '--px': '-1.8rem',
      '--py': '-1rem',
    },
  },
  {
    src: '/PNG/CHOCOLATE.png',
    style: {
      '--x': '33.3vw',
      '--y': '48.7vh',
      '--w': '5.2rem',
      '--r': '-31deg',
      '--rainDelay': '0.56s',
      '--rainDuration': '1.22s',
      '--fall': '78vh',
      '--duration': '7.4s',
      '--blur': '0.1px',
      '--opacity': '0.92',
      '--dx': '0.5rem',
      '--dy': '-0.75rem',
      '--spin': '6deg',
      '--px': '1.4rem',
      '--py': '0.75rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '34.8vw',
      '--y': '62vh',
      '--w': '5.4rem',
      '--r': '-23deg',
      '--rainDelay': '0.82s',
      '--rainDuration': '1.34s',
      '--fall': '88vh',
      '--duration': '8s',
      '--blur': '0',
      '--opacity': '0.92',
      '--dx': '-0.4rem',
      '--dy': '-0.8rem',
      '--spin': '-5deg',
      '--px': '1.25rem',
      '--py': '0.72rem',
    },
  },
  {
    src: '/PNG/POHA.png',
    style: {
      '--x': '43.3vw',
      '--y': '25.4vh',
      '--w': '2.7rem',
      '--r': '18deg',
      '--rainDelay': '1.02s',
      '--rainDuration': '1.12s',
      '--fall': '70vh',
      '--duration': '6.4s',
      '--blur': '1px',
      '--opacity': '0.64',
      '--dx': '0.24rem',
      '--dy': '-0.55rem',
      '--spin': '8deg',
      '--px': '-0.74rem',
      '--py': '-0.44rem',
    },
  },
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '45.6vw',
      '--y': '9.5vh',
      '--w': '4.3rem',
      '--r': '34deg',
      '--rainDelay': '0.48s',
      '--rainDuration': '1.22s',
      '--fall': '66vh',
      '--duration': '7.4s',
      '--blur': '0',
      '--opacity': '0.92',
      '--dx': '-0.45rem',
      '--dy': '-0.75rem',
      '--spin': '6deg',
      '--px': '-1.35rem',
      '--py': '-0.8rem',
    },
  },
  {
    src: '/PNG/JAGGERY.png',
    style: {
      '--x': '47.2vw',
      '--y': '68.8vh',
      '--w': '4.8rem',
      '--r': '44deg',
      '--rainDelay': '0.44s',
      '--rainDuration': '1.42s',
      '--fall': '92vh',
      '--duration': '8.8s',
      '--blur': '0.2px',
      '--opacity': '0.8',
      '--dx': '0.35rem',
      '--dy': '-0.65rem',
      '--spin': '8deg',
      '--px': '1.15rem',
      '--py': '0.68rem',
    },
  },
  {
    src: '/PNG/POHA.png',
    style: {
      '--x': '40.8vw',
      '--y': '74vh',
      '--w': '2.45rem',
      '--r': '-42deg',
      '--rainDelay': '1.18s',
      '--rainDuration': '1.1s',
      '--fall': '90vh',
      '--duration': '6.8s',
      '--blur': '1.25px',
      '--opacity': '0.5',
      '--dx': '0.2rem',
      '--dy': '-0.42rem',
      '--spin': '-10deg',
      '--px': '0.62rem',
      '--py': '0.38rem',
    },
  },

  // ── CENTER–RIGHT (50–69vw) ───────────────────────────────────
  {
    src: '/PNG/POHA.png',
    style: {
      '--x': '51vw',
      '--y': '12.6vh',
      '--w': '3.3rem',
      '--r': '-15deg',
      '--rainDelay': '0.2s',
      '--rainDuration': '1.18s',
      '--fall': '58vh',
      '--duration': '7s',
      '--blur': '0',
      '--opacity': '0.82',
      '--dx': '0.35rem',
      '--dy': '-0.6rem',
      '--spin': '-7deg',
      '--px': '-1rem',
      '--py': '-0.55rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '52.7vw',
      '--y': '20.8vh',
      '--w': '4.25rem',
      '--r': '-36deg',
      '--rainDelay': '0.14s',
      '--rainDuration': '1.18s',
      '--fall': '74vh',
      '--duration': '7.2s',
      '--blur': '0.35px',
      '--opacity': '0.84',
      '--dx': '-0.32rem',
      '--dy': '-0.7rem',
      '--spin': '-7deg',
      '--px': '-1.1rem',
      '--py': '-0.62rem',
    },
  },
  {
    src: '/PNG/CHOCOLATE.png',
    style: {
      '--x': '57vw',
      '--y': '6.6vh',
      '--w': '7.6rem',
      '--r': '13deg',
      '--rainDelay': '0.38s',
      '--rainDuration': '1.3s',
      '--fall': '70vh',
      '--duration': '8.4s',
      '--blur': '0',
      '--opacity': '0.96',
      '--dx': '0.4rem',
      '--dy': '-1rem',
      '--spin': '5deg',
      '--px': '-2.05rem',
      '--py': '-1.15rem',
    },
  },
  {
    src: '/PNG/POHA.png',
    style: {
      '--x': '56.3vw',
      '--y': '63.8vh',
      '--w': '3.2rem',
      '--r': '38deg',
      '--rainDelay': '0.95s',
      '--rainDuration': '1.08s',
      '--fall': '84vh',
      '--duration': '6.9s',
      '--blur': '0.2px',
      '--opacity': '0.7',
      '--dx': '0.28rem',
      '--dy': '-0.52rem',
      '--spin': '8deg',
      '--px': '0.9rem',
      '--py': '0.48rem',
    },
  },
  {
    src: '/PNG/JAGGERY.png',
    style: {
      '--x': '60.6vw',
      '--y': '31.2vh',
      '--w': '3.8rem',
      '--r': '28deg',
      '--rainDelay': '0.88s',
      '--rainDuration': '1.3s',
      '--fall': '78vh',
      '--duration': '8.4s',
      '--blur': '1.35px',
      '--opacity': '0.58',
      '--dx': '0.3rem',
      '--dy': '-0.62rem',
      '--spin': '9deg',
      '--px': '-0.82rem',
      '--py': '-0.5rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '63.7vw',
      '--y': '57.6vh',
      '--w': '4.6rem',
      '--r': '14deg',
      '--rainDelay': '0.72s',
      '--rainDuration': '1.26s',
      '--fall': '82vh',
      '--duration': '7.4s',
      '--blur': '0',
      '--opacity': '0.9',
      '--dx': '0.45rem',
      '--dy': '-0.75rem',
      '--spin': '5deg',
      '--px': '1.35rem',
      '--py': '0.78rem',
    },
  },
  {
    src: '/PNG/ELAICHI.png',
    style: {
      '--x': '64.8vw',
      '--y': '3.4vh',
      '--w': '1.6rem',
      '--r': '-11deg',
      '--rainDelay': '1.12s',
      '--rainDuration': '0.98s',
      '--fall': '56vh',
      '--duration': '6.1s',
      '--blur': '0.65px',
      '--opacity': '0.72',
      '--dx': '0.18rem',
      '--dy': '-0.48rem',
      '--spin': '-10deg',
      '--px': '-0.52rem',
      '--py': '-0.3rem',
    },
  },
  {
    src: '/PNG/JAGGERY.png',
    style: {
      '--x': '67.2vw',
      '--y': '72.4vh',
      '--w': '4.1rem',
      '--r': '-12deg',
      '--rainDelay': '0.66s',
      '--rainDuration': '1.34s',
      '--fall': '92vh',
      '--duration': '8.1s',
      '--blur': '1.55px',
      '--opacity': '0.54',
      '--dx': '-0.28rem',
      '--dy': '-0.58rem',
      '--spin': '8deg',
      '--px': '0.72rem',
      '--py': '0.42rem',
    },
  },
  {
    src: '/PNG/DATES.png',
    style: {
      '--x': '68.7vw',
      '--y': '7.2vh',
      '--w': '9.3rem',
      '--r': '7deg',
      '--rainDelay': '0.62s',
      '--rainDuration': '1.48s',
      '--fall': '84vh',
      '--duration': '9.2s',
      '--blur': '0',
      '--opacity': '0.98',
      '--dx': '-0.45rem',
      '--dy': '-1.05rem',
      '--spin': '-5deg',
      '--px': '-2.5rem',
      '--py': '-1.28rem',
    },
  },

  // ── RIGHT (70–89vw) ──────────────────────────────────────────
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '70.4vw',
      '--y': '24.2vh',
      '--w': '2.95rem',
      '--r': '-64deg',
      '--rainDelay': '0.58s',
      '--rainDuration': '1.06s',
      '--fall': '66vh',
      '--duration': '6.7s',
      '--blur': '1.6px',
      '--opacity': '0.52',
      '--dx': '-0.2rem',
      '--dy': '-0.4rem',
      '--spin': '11deg',
      '--px': '-0.7rem',
      '--py': '-0.38rem',
    },
  },
  {
    src: '/PNG/ELAICHI.png',
    style: {
      '--x': '72.8vw',
      '--y': '51.4vh',
      '--w': '2.2rem',
      '--r': '-29deg',
      '--rainDelay': '0.84s',
      '--rainDuration': '1.02s',
      '--fall': '80vh',
      '--duration': '6.4s',
      '--blur': '0.2px',
      '--opacity': '0.76',
      '--dx': '-0.28rem',
      '--dy': '-0.54rem',
      '--spin': '-7deg',
      '--px': '0.75rem',
      '--py': '0.42rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '74.8vw',
      '--y': '-1.4vh',
      '--w': '6.4rem',
      '--r': '-17deg',
      '--rainDelay': '0.05s',
      '--rainDuration': '1.18s',
      '--fall': '54vh',
      '--duration': '7.8s',
      '--blur': '0',
      '--opacity': '0.96',
      '--dx': '0.45rem',
      '--dy': '-0.8rem',
      '--spin': '6deg',
      '--px': '-1.75rem',
      '--py': '-0.9rem',
    },
  },
  {
    src: '/PNG/CHOCOLATE.png',
    style: {
      '--x': '76.8vw',
      '--y': '31.6vh',
      '--w': '3.6rem',
      '--r': '46deg',
      '--rainDelay': '0.74s',
      '--rainDuration': '1.22s',
      '--fall': '76vh',
      '--duration': '7.8s',
      '--blur': '0.85px',
      '--opacity': '0.66',
      '--dx': '0.26rem',
      '--dy': '-0.58rem',
      '--spin': '-8deg',
      '--px': '-0.95rem',
      '--py': '-0.52rem',
    },
  },
  {
    src: '/PNG/ELAICHI.png',
    style: {
      '--x': '78.5vw',
      '--y': '10.8vh',
      '--w': '2.35rem',
      '--r': '24deg',
      '--rainDelay': '0.92s',
      '--rainDuration': '1.05s',
      '--fall': '52vh',
      '--duration': '6.6s',
      '--blur': '0.2px',
      '--opacity': '0.82',
      '--dx': '0.32rem',
      '--dy': '-0.7rem',
      '--spin': '7deg',
      '--px': '-0.8rem',
      '--py': '-0.45rem',
    },
  },
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '80.6vw',
      '--y': '58.7vh',
      '--w': '3.7rem',
      '--r': '-57deg',
      '--rainDelay': '0.18s',
      '--rainDuration': '1.14s',
      '--fall': '76vh',
      '--duration': '7.1s',
      '--blur': '0',
      '--opacity': '0.92',
      '--dx': '-0.5rem',
      '--dy': '-0.65rem',
      '--spin': '-8deg',
      '--px': '1rem',
      '--py': '0.58rem',
    },
  },
  {
    src: '/PNG/JAGGERY.png',
    style: {
      '--x': '82.5vw',
      '--y': '16.2vh',
      '--w': '5.1rem',
      '--r': '-18deg',
      '--rainDelay': '0.34s',
      '--rainDuration': '1.36s',
      '--fall': '72vh',
      '--duration': '8.1s',
      '--blur': '0',
      '--opacity': '0.9',
      '--dx': '0.42rem',
      '--dy': '-0.72rem',
      '--spin': '7deg',
      '--px': '-1.55rem',
      '--py': '-0.85rem',
    },
  },
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '85.6vw',
      '--y': '3.2vh',
      '--w': '3.4rem',
      '--r': '52deg',
      '--rainDelay': '0.76s',
      '--rainDuration': '1.12s',
      '--fall': '60vh',
      '--duration': '6.8s',
      '--blur': '0',
      '--opacity': '0.9',
      '--dx': '-0.35rem',
      '--dy': '-0.65rem',
      '--spin': '-6deg',
      '--px': '-0.95rem',
      '--py': '-0.5rem',
    },
  },
  {
    src: '/PNG/POHA.png',
    style: {
      '--x': '87.4vw',
      '--y': '42.8vh',
      '--w': '2.9rem',
      '--r': '-38deg',
      '--rainDelay': '0.64s',
      '--rainDuration': '1.1s',
      '--fall': '80vh',
      '--duration': '6.9s',
      '--blur': '1.3px',
      '--opacity': '0.56',
      '--dx': '0.22rem',
      '--dy': '-0.46rem',
      '--spin': '9deg',
      '--px': '-0.6rem',
      '--py': '-0.38rem',
    },
  },

  // ── FAR RIGHT (90–100vw) ─────────────────────────────────────
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '88.6vw',
      '--y': '24.8vh',
      '--w': '2.3rem',
      '--r': '22deg',
      '--rainDelay': '1.26s',
      '--rainDuration': '1.04s',
      '--fall': '62vh',
      '--duration': '6.2s',
      '--blur': '1.9px',
      '--opacity': '0.48',
      '--dx': '-0.18rem',
      '--dy': '-0.36rem',
      '--spin': '9deg',
      '--px': '-0.5rem',
      '--py': '-0.3rem',
    },
  },
  {
    src: '/PNG/CHOCOLATE.png',
    style: {
      '--x': '89.2vw',
      '--y': '54.2vh',
      '--w': '4.7rem',
      '--r': '22deg',
      '--rainDelay': '0.52s',
      '--rainDuration': '1.3s',
      '--fall': '82vh',
      '--duration': '7.9s',
      '--blur': '0.1px',
      '--opacity': '0.9',
      '--dx': '0.4rem',
      '--dy': '-0.8rem',
      '--spin': '6deg',
      '--px': '1.25rem',
      '--py': '0.72rem',
    },
  },
  {
    src: '/PNG/OAT.png',
    style: {
      '--x': '92.2vw',
      '--y': '11.5vh',
      '--w': '2.9rem',
      '--r': '-46deg',
      '--rainDelay': '0.68s',
      '--rainDuration': '1.06s',
      '--fall': '58vh',
      '--duration': '6.6s',
      '--blur': '0',
      '--opacity': '0.8',
      '--dx': '-0.32rem',
      '--dy': '-0.58rem',
      '--spin': '-8deg',
      '--px': '-0.8rem',
      '--py': '-0.42rem',
    },
  },
  {
    src: '/PNG/PEANUTS.png',
    style: {
      '--x': '92.4vw',
      '--y': '38.5vh',
      '--w': '3.75rem',
      '--r': '35deg',
      '--rainDelay': '0.46s',
      '--rainDuration': '1.28s',
      '--fall': '78vh',
      '--duration': '7.5s',
      '--blur': '0.7px',
      '--opacity': '0.68',
      '--dx': '-0.26rem',
      '--dy': '-0.55rem',
      '--spin': '-7deg',
      '--px': '-0.78rem',
      '--py': '-0.48rem',
    },
  },
  {
    src: '/PNG/DATES.png',
    style: {
      '--x': '96.8vw',
      '--y': '4.5vh',
      '--w': '6.1rem',
      '--r': '-19deg',
      '--rainDelay': '0.18s',
      '--rainDuration': '1.34s',
      '--fall': '74vh',
      '--duration': '8.6s',
      '--blur': '1.45px',
      '--opacity': '0.46',
      '--dx': '-0.28rem',
      '--dy': '-0.64rem',
      '--spin': '6deg',
      '--px': '-1.2rem',
      '--py': '-0.68rem',
    },
  },
];

const compactIngredients = ingredients.filter((_, index) => index % 2 === 0);
const compactMediaQuery = '(max-width: 900px), (prefers-reduced-motion: reduce)';

const getOptimizedIngredientSrc = (src: string) => {
  const fileName = src
    .split('/')
    .pop()
    ?.replace('.png', '.webp')
    .toLowerCase()
    .replace(/_/g, '-');

  return `/optimized/ingredients/${fileName}`;
};

function useCompactIngredientStage() {
  const [isCompact, setIsCompact] = useState(true);

  useEffect(() => {
    const media = window.matchMedia(compactMediaQuery);
    const update = () => setIsCompact(media.matches);

    update();
    media.addEventListener('change', update);

    return () => media.removeEventListener('change', update);
  }, []);

  return isCompact;
}

export default function IngredientStage() {
  const isCompact = useCompactIngredientStage();
  const visibleIngredients = useMemo(
    () => (isCompact ? compactIngredients : ingredients),
    [isCompact]
  );

  return (
    <div className={styles.ingredientStage} aria-hidden="true">
      {visibleIngredients.map((ingredient) => (
        <span
          key={`${ingredient.src}-${ingredient.style['--x']}-${ingredient.style['--y']}`}
          className={styles.ingredientDrop}
          style={ingredient.style}
        >
          <img
            className={styles.ingredientSprite}
            src={getOptimizedIngredientSrc(ingredient.src)}
            alt=""
            width={360}
            height={360}
            loading="lazy"
            decoding="async"
            fetchPriority="low"
            draggable={false}
          />
        </span>
      ))}
    </div>
  );
}
